version: '3.10'
services:
  postgres_db:
    container_name: altay_rest_postgres
    image: postgres:16.0-alpine
    volumes:
      - altay_rest_postgres_data:/var/lib/postgresql/altay_rest_backend_data_pg_data/
    environment:
      POSTGRES_DB: "altay_rest"
      POSTGRES_USER: "altay_rest"
      POSTGRES_PASSWORD: "altay_rest"
    ports:
      - "5432:5432"
#    expose: [ 5432 ]

  redis:
    container_name: altay_rest
    image: redis:alpine
    hostname: redis
    volumes:
      - altay_rest_redis_data:/data
    ports:
      - 6379:6379
    expose: [ 6379 ]
volumes:
  altay_rest_postgres_data:
  altay_rest_redis_data:
